# Generated by Django 4.1.7 on 2023-06-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField()),
                ('hash', models.TextField()),
                ('prev_hash', models.TextField()),
                ('nonce', models.IntegerField(default=0)),
            ],
        ),
    ]
