# Generated by Django 4.1.7 on 2023-07-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userlogin', '0002_alter_patient_height_alter_patient_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('advice', models.TextField(blank=True, null=True)),
                ('prescribed_on', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_by', to='userlogin.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_to', to='userlogin.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=500)),
                ('medicine_type', models.CharField(choices=[('t', 'Tablet'), ('c', 'Capsule'), ('s', 'Syrup')], max_length=50)),
                ('before_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('after_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('before_lunch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('after_lunch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('before_dinner', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evening', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('after_dinner', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tablets', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='doctor.prescription')),
            ],
        ),
    ]
